export const GET_FILMS_LOADING = 'GET_REC_LOADING';
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS';
export const GET_FILMS_ERROR = 'GET_FILMS_ERROR';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';

export const GET_ONE_FILM_LOADING = 'GET_ONE_FILM_LOADING';
export const GET_ONE_FILM_SUCCESS = 'GET_ONE_FILM_SUCCESS';
export const GET_ONE_FILM_ERROR = 'GET_ONE_FILM_ERROR';

export const GET_GENRES_LOADING = 'GET_GENRES_LOADING';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_ERROR = 'GET_GENRES_ERROR';

export const GET_REC_LOADING = 'GET_REC_LOADING';
export const GET_REC_SUCCESS = 'GET_REC_SUCCESS';
export const GET_REC_ERROR = 'GET_REC_ERROR';

export const GET_SIMILAR_LOADING = 'GET_SIMILAR_LOADING';
export const GET_SIMILAR_SUCCESS = 'GET_SIMILAR_SUCCESS';
export const GET_SIMILAR_ERROR = 'GET_SIMILAR_ERROR';
