export const GET_FILMS_LOADING = 'GET_FILMS_LOADING';
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS';
export const GET_FILMS_ERROR = 'GET_FILMS_ERROR';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
